#+Title: Rust workshop material
#+Author: Katharina Fey
#+SETUPFILE: html.setup

  Welcome to the Rust teaching material repository.  This material was
  created by [[https://spacekookie.de][Katharina Fey]] with the purpose of having a set of slides,
  code examples, example projects, and advanced visualisations to
  teach the Rust programming language to developers of varying
  backgrounds.

  Is your company looking for teaching?  [[mailto:kookie@spacekookie.de][Contact me]] for details and
  booking!

* Outline

   This repository is structured as a set of course trees.  Each tree
   focuses primarily on conveying a single aspect of the Rust
   programming langueg.  Following is an overview of available
   courses.

   - [[./cc-tree-days][rust-three-days]] :: A comprehensive introductory course that will
     get developers, who are completely unfamiliar with Rust into the
     position to write complex systems applications and libraries
   - [[./dd-ownership][deep-dive-ownership]]  :: An intensive deep-dive course into the
     Rust ownership model and it's impact on concurrent programming
   - [[./dd-async/README.org][deep-dive-async]]     :: A deep-dive course into async development,
     async compiler internals, and runtime development in Rust

* Build these slides

   It's generally recommended to use the [[https://git.irde.st/kookiespace/teaching-rust/-/][CI artifacts]] for these
   slides, but if you must build them yourself, you need to have Emacs
   (v26+) and org-mode installed!

   The following function will export the full course into an HTML
   slide tree.
   
   #+INCLUDE: "ci/export-course.el" src emacs-lisp


