#+Title: Rust ownership deep-dive
#+Author: Katharina Fey
#+SETUPFILE: ../html.setup

* Introduction

  This is an _beginner level_ course, targeted at developers who have
  _little to no Rust experience_.  Some _general programming_
  experience can be helpful, but is not required.

* Course outline

  + [[file:10-memory-management.org][Memory management basics]]
  + [[file:20-why-ownership.org][Why ownership?]]
  + [[file:21-thought-on-raii.org][A thought on RAII]]
  + [[file:25-ownership-quiz.org][Exercise: seizing ownership]]
  + [[file:30-borrowing.org][Borrowing]]
  + [[file:40-lifetimes.org][Lifetimes]]
  + [[file:35-borrowing-exercises.org][Exercise: lend me your T]]
  + [[file:50-threading.org][Threading & Ownership]]
  + [[file:51-race-conditians.org][Thoughts on race conditions]]
  + [[file:55-thread-exercises.org][Exercise: concurrently borrowing stuff]]
  + Concurrency patterns: Arc & Mutex
  + Concurrency patterns: Channels
  + Advanced Exercise: Load-balanced web server

  \\

  + [[https://git.irde.st/kookiespace/teaching-rust/-/tree/main/dd-ownership/exercises][Exercise overview]]
  
* About these slides

  You can find a copy of these slides at
  https://teach.spacekookie.de/rust/ownership!  If you find any
  mistakes, please feel free to send a merge-request on [[https://git.irde.st/kookiespace/teaching-rust/][Gitlab]]!

* How to build

  These slide-decks are built with emacs and [[https://orgmode.org][org-mode]].  The following
  function will export the full course into an HTML slide tree.

  #+INCLUDE: "../ci/export-course.el" src emacs-lisp
   
* License

  This course, as well as any associated media assets is licensed
  under Creative Commons CC-BY-SA 4.0.  All associated code examples
  are licensed under the GNU General Public License Version 3.0 (or
  later).

  See the [[../licenses][licenses]] directory for complete copies of the applicable
  license texts.
