#+Title: Rust async deep-dive course
#+Author: Katharina Fey
#+SETUPFILE: ../html.setup

* Introduction

  This is an _intermediate level_ course, targeted at developers who
  have at least _some familiarity with Rust and async development_
  models.

* Course outline

   + [[./010-what-is-async.org][Async theory: what is async?]]
   + [[file:020-async-in-core-std.org][Async foundations in core/std]]
   + [[file:030-future-anatomy.org][Anatomy of a basic Future]]
   + [[file:060-exercise-timer.org][Exercise: Timer Future]]
   + [[file:035-async-patterns.org][Basic async patterns]]
   + [[file:050-runtimes.org][Dive into runtimes]]
   + [[file:040-shutdown-select.org][Future pattern: shutdown select]]
   + [[file:055-futures-wakenotify.org][Future pattern: WakeNotify]]
   + [[file:057-actor-programming.org][Side-track: Actor programming]]
   + [[file:061-exercise-reactor.org][Exercises]]

   \\

   + [[https://git.irde.st/kookiespace/teaching-rust/-/tree/main/dd-async/exercises][Exercise overview]]

   
* Build these slides

   It's generally recommended to use the [[https://git.irde.st/kookiespace/teaching-rust/-/jobs][CI artifacts]] for these
   slides, but if you must build them yourself, you need to have Emacs
   (v26+) and org-mode installed!

   The following function will export the full course into an HTML
   slide tree.

   #+INCLUDE: "../ci/export-course.el" src emacs-lisp
   
* License

   This course, as well as any associated media assets is licensed
   under Creative Commons CC-BY-SA 3.0.  All associated code examples
   are licensed under the GNU General Public License Version 3.0 (or
   later).

   See the [[../licenses][licenses]] directory for complete copies of the applicable
   license texts.
