#+Title: Rust async deep-dive course
#+Author: Katharina Fey
#+SETUPFILE: ../html.setup

* Introduction

  This is an _intermediate level_ course, targeted at developers who
  have at least _some familiarity with Rust and async development_
  models.

* Course outline

   + [[./010-what-is-async.org][Async theory: what is async?]]
   + [[file:020-async-in-core-std.org][Async foundations in core/std]]
   + Writing a Future
   + Runtimes
   + Excursion: scheduling
   + Excursion: channels & backpressure
   + Tasks, futures, and threads
   + 

* Build these slides

   It's generally recommended to use the [[https://git.irde.st/kookiespace/teaching-rust/-/jobs][CI artifacts]] for these
   slides, but if you must build them yourself, you need to have Emacs
   (v26+) and org-mode installed!

   The following function will export the full course into an HTML
   slide tree.
   
   #+BEGIN_SRC emacs-lisp
     ;; TODO: swap the theme to be more easily readable on white background
     (defun export-course ()
       "Export a course tree as a set of HTML files"
       (interactive)
     
       ;; Make sure org-reveal is loaded and set-up
       (load-library "reveal")
       (setq org-reveal-root "../.templates")
     
       ;; (print custom-enabled-themes)
     
       ;; Export the README
       (find-file "README.org")
       (org-html-export-to-html)
     
       ;; Then export the rest of the slides
       (defvar slides (delete "README.org" (directory-files "." nil "\.org$" t)))
       (mapcar
        (lambda (file)
          (find-file file)
          (org-reveal-export-to-html))
        slides))
   #+END_SRC
   
* License

   This course, as well as any associated media assets is licensed
   under the GNU Free Documentation License Version 1.3 (or later).
   All associated code examples are licensed under the GNU General
   Public License Version 3.0 (or later).

   See the [[../licenses][licenses]] directory for complete copies of the applicable
   license texts.

